### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by SaraSlm** [ServiceNow/beyond-trivial-explanations#4]
hello,
I want to train it to reproduce the results again(just to learn) but I got an error on the third command(python trainval.py -e oracle -sb ./logs/oracle -d ./data -r 1)
my error:

Traceback (most recent call last):
  File "/content/beyond-trivial-explanations/trainval.py", line 140, in <module>
    hw.run_wizard(func=trainval,
  File "/usr/local/lib/python3.10/dist-packages/haven/haven_wizard.py", line 99, in run_wizard
    exp_list += exp_groups[exp_group_name]
KeyError: 'oracle'

to solve this problem although I don't know if it is true or not... I replaced "oracle" with "cls_oracle" and I run the command below:
python trainval.py -e cls_oracle -sb ./logs/oracle -d ./data -r 1
again this time I got the below error:
FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained_models/resnet50_128.pth'

can you please help me...

**Comment by prlz77** [comment]
Hi, thanks for the interest in our work! Did you download the pre-trained models from Zenodo? (https://github.com/ServiceNow/beyond-trivial-explanations#2-generate-counterfactuals-for-pre-trained-models)

**Comment by prlz77** [comment]
Hi Sara,

Thank you for the interest in our work! Our oracle is based on the VGG_Faces2 [ResNet-50-128D](https://github.com/ox-vgg/vgg_face2). You need to download it and put it in `./data`.

I am going to update the readme with this info.

Best,

Pau

**Comment by huifenghc** [comment]
Hello

I am quite interested in your DiVE job, but the download link for the VGG_Faces2 [ResNet-50-128D](https://github.com/ox-vgg/vgg_face2) weight file has expired. Do you have any other methods to obtain this file? If you still keep this file, could you share it with me? my email is yangchen23@mails.ucas.ac.cn

Thank you.

**Comment by prlz77** [comment]
Hello!Unfortunately the expired link belongs to Oxford university (the owners of the model) and I do not have any copy. There seems to have been some legal issue with images contained in VGG leading authors to delete all content from the Internet :(weights' links are not working. · Issue #57 · ox-vgg/vgg_face2github.comPauEl 23 nov. 2023, a les 9:59, huifenghc ***@***.***> va escriure:﻿
Hello
I am quite interested in your DiVE job, but the download link for the VGG_Faces2 ResNet-50-128D weight file has expired. Do you have any other methods to obtain this file? If you still keep this file, could you share it with me? my email is ***@***.***
Thank you.
